apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DB_HOST: postgres-service.{{ .Release.Namespace }}.svc.cluster.local
  DB_PORT: "5432"
  DB_NAME: {{ .Values.postgresql.database }}
