apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  labels:
    app: fastapi
    release: {{ .Release.Name }}
spec:
  selector:
    app: fastapi
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
